# Generated by Django 3.1.1 on 2021-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='toq',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='accs.Question'),
        ),
    ]
