# Generated by Django 3.1.1 on 2021-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0002_auto_20210617_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='360', max_length=200, null=True),
        ),
    ]
