# Generated by Django 3.1.1 on 2021-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0003_auto_20210617_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='val',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], null=True),
        ),
    ]
